YOUTUBE_API_KEY = "AIzaSyCAqlVAVcyosvEfKngOaDrLMSqmy7WcnNM"

[snowflake]
user = "TINAGODATALABS"
password = "1990Snowflake!"
account = "FISTFNF-AIB47082"
warehouse = "COMPUTE_WH"
database = "TEAM5PM_PRODUCT"
schema = "GOLD"
role = "ACCOUNTADMIN"
YOUTUBE_API_KEY = "AIzaSyCAqlVAVcyosvEfKngOaDrLMSqmy7WcnNM"